// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type skmsgSockKey struct {
	_     structs.HostLayout
	Sip   uint32
	Dip   uint32
	Sport uint32
	Dport uint32
}

type skmsgStatsValue struct {
	_           structs.HostLayout
	RxPackets   uint64
	RxBytes     uint64
	PassPackets uint64
	DropPackets uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	skmsgMapSockHash           = "sock_hash"
	skmsgMapSockopsStatsMap    = "sockops_stats_map"
	skmsgProgProxyRedirectFunc = "proxy_redirect_func"
)

// loadSkmsg returns the embedded CollectionSpec for skmsg.
func loadSkmsg() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SkmsgBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load skmsg: %w", err)
	}

	return spec, err
}

// loadSkmsgObjects loads skmsg and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*skmsgObjects
//	*skmsgPrograms
//	*skmsgMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSkmsgObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSkmsg()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// skmsgSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type skmsgSpecs struct {
	skmsgProgramSpecs
	skmsgMapSpecs
	skmsgVariableSpecs
}

// skmsgProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type skmsgProgramSpecs struct {
	ProxyRedirectFunc *ebpf.ProgramSpec `ebpf:"proxy_redirect_func"`
}

// skmsgMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type skmsgMapSpecs struct {
	SockHash        *ebpf.MapSpec `ebpf:"sock_hash"`
	SockopsStatsMap *ebpf.MapSpec `ebpf:"sockops_stats_map"`
}

// skmsgVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type skmsgVariableSpecs struct {
}

// skmsgObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSkmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type skmsgObjects struct {
	skmsgPrograms
	skmsgMaps
	skmsgVariables
}

func (o *skmsgObjects) Close() error {
	return _SkmsgClose(
		&o.skmsgPrograms,
		&o.skmsgMaps,
	)
}

// skmsgMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSkmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type skmsgMaps struct {
	SockHash        *ebpf.Map `ebpf:"sock_hash"`
	SockopsStatsMap *ebpf.Map `ebpf:"sockops_stats_map"`
}

func (m *skmsgMaps) Close() error {
	return _SkmsgClose(
		m.SockHash,
		m.SockopsStatsMap,
	)
}

// skmsgVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSkmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type skmsgVariables struct {
}

// skmsgPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSkmsgObjects or ebpf.CollectionSpec.LoadAndAssign.
type skmsgPrograms struct {
	ProxyRedirectFunc *ebpf.Program `ebpf:"proxy_redirect_func"`
}

func (p *skmsgPrograms) Close() error {
	return _SkmsgClose(
		p.ProxyRedirectFunc,
	)
}

func _SkmsgClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed skmsg_bpf.o
var _SkmsgBytes []byte
