// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sockopsSockKey struct {
	_     structs.HostLayout
	Sip   uint32
	Dip   uint32
	Sport uint32
	Dport uint32
}

type sockopsStatsValue struct {
	_           structs.HostLayout
	RxPackets   uint64
	RxBytes     uint64
	PassPackets uint64
	DropPackets uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	sockopsMapAuditRingbuf         = "audit_ringbuf"
	sockopsMapSockHash             = "sock_hash"
	sockopsMapSockopsStatsMap      = "sockops_stats_map"
	sockopsProgSockopsIdentityFunc = "sockops_identity_func"
)

// loadSockops returns the embedded CollectionSpec for sockops.
func loadSockops() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SockopsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sockops: %w", err)
	}

	return spec, err
}

// loadSockopsObjects loads sockops and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sockopsObjects
//	*sockopsPrograms
//	*sockopsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSockopsObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSockops()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sockopsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockopsSpecs struct {
	sockopsProgramSpecs
	sockopsMapSpecs
	sockopsVariableSpecs
}

// sockopsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockopsProgramSpecs struct {
	SockopsIdentityFunc *ebpf.ProgramSpec `ebpf:"sockops_identity_func"`
}

// sockopsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockopsMapSpecs struct {
	AuditRingbuf    *ebpf.MapSpec `ebpf:"audit_ringbuf"`
	SockHash        *ebpf.MapSpec `ebpf:"sock_hash"`
	SockopsStatsMap *ebpf.MapSpec `ebpf:"sockops_stats_map"`
}

// sockopsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sockopsVariableSpecs struct {
}

// sockopsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockopsObjects struct {
	sockopsPrograms
	sockopsMaps
	sockopsVariables
}

func (o *sockopsObjects) Close() error {
	return _SockopsClose(
		&o.sockopsPrograms,
		&o.sockopsMaps,
	)
}

// sockopsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockopsMaps struct {
	AuditRingbuf    *ebpf.Map `ebpf:"audit_ringbuf"`
	SockHash        *ebpf.Map `ebpf:"sock_hash"`
	SockopsStatsMap *ebpf.Map `ebpf:"sockops_stats_map"`
}

func (m *sockopsMaps) Close() error {
	return _SockopsClose(
		m.AuditRingbuf,
		m.SockHash,
		m.SockopsStatsMap,
	)
}

// sockopsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockopsVariables struct {
}

// sockopsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSockopsObjects or ebpf.CollectionSpec.LoadAndAssign.
type sockopsPrograms struct {
	SockopsIdentityFunc *ebpf.Program `ebpf:"sockops_identity_func"`
}

func (p *sockopsPrograms) Close() error {
	return _SockopsClose(
		p.SockopsIdentityFunc,
	)
}

func _SockopsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockops_bpf.o
var _SockopsBytes []byte
