// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcFlowKey struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	Pad      [3]uint8
}

type tcFlowState struct {
	_        structs.HostLayout
	State    uint32
	_        [4]byte
	Packets  uint64
	Bytes    uint64
	LastSeen uint64
	Flags    uint32
	Pad      uint32
}

type tcStatsValue struct {
	_           structs.HostLayout
	RxPackets   uint64
	RxBytes     uint64
	PassPackets uint64
	DropPackets uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tcMapAuditRingbuf    = "audit_ringbuf"
	tcMapConntrackMap    = "conntrack_map"
	tcMapTcStatsMap      = "tc_stats_map"
	tcProgTcFirewallFunc = "tc_firewall_func"
)

// loadTc returns the embedded CollectionSpec for tc.
func loadTc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tc: %w", err)
	}

	return spec, err
}

// loadTcObjects loads tc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcObjects
//	*tcPrograms
//	*tcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcSpecs struct {
	tcProgramSpecs
	tcMapSpecs
	tcVariableSpecs
}

// tcProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcProgramSpecs struct {
	TcFirewallFunc *ebpf.ProgramSpec `ebpf:"tc_firewall_func"`
}

// tcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcMapSpecs struct {
	AuditRingbuf *ebpf.MapSpec `ebpf:"audit_ringbuf"`
	ConntrackMap *ebpf.MapSpec `ebpf:"conntrack_map"`
	TcStatsMap   *ebpf.MapSpec `ebpf:"tc_stats_map"`
}

// tcVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcVariableSpecs struct {
}

// tcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcObjects struct {
	tcPrograms
	tcMaps
	tcVariables
}

func (o *tcObjects) Close() error {
	return _TcClose(
		&o.tcPrograms,
		&o.tcMaps,
	)
}

// tcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcMaps struct {
	AuditRingbuf *ebpf.Map `ebpf:"audit_ringbuf"`
	ConntrackMap *ebpf.Map `ebpf:"conntrack_map"`
	TcStatsMap   *ebpf.Map `ebpf:"tc_stats_map"`
}

func (m *tcMaps) Close() error {
	return _TcClose(
		m.AuditRingbuf,
		m.ConntrackMap,
		m.TcStatsMap,
	)
}

// tcVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcVariables struct {
}

// tcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcPrograms struct {
	TcFirewallFunc *ebpf.Program `ebpf:"tc_firewall_func"`
}

func (p *tcPrograms) Close() error {
	return _TcClose(
		p.TcFirewallFunc,
	)
}

func _TcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_bpf.o
var _TcBytes []byte
