// Code generated by bpf2go; DO NOT EDIT.

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type xdpCgroupKey struct {
	_        structs.HostLayout
	Gen      uint32
	Pad      uint32
	CgroupId uint64
}

type xdpLpmKeyIpv4 struct {
	_         structs.HostLayout
	Prefixlen uint32
	Gen       uint32
	Addr      uint32
}

type xdpPortRuleKey struct {
	_        structs.HostLayout
	Gen      uint32
	DstPort  uint16
	Protocol uint8
	Pad      uint8
}

type xdpPortRuleVal struct {
	_      structs.HostLayout
	Action uint32
	RuleId uint32
}

type xdpStatsValue struct {
	_           structs.HostLayout
	RxPackets   uint64
	RxBytes     uint64
	PassPackets uint64
	DropPackets uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	xdpMapActiveGenerationMap = "active_generation_map"
	xdpMapAuditRingbuf        = "audit_ringbuf"
	xdpMapCgroupIdentityMap   = "cgroup_identity_map"
	xdpMapLpmBlocklist        = "lpm_blocklist"
	xdpMapPortRulesMap        = "port_rules_map"
	xdpMapXdpStatsMap         = "xdp_stats_map"
	xdpProgXdpFirewallFunc    = "xdp_firewall_func"
)

// loadXdp returns the embedded CollectionSpec for xdp.
func loadXdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp: %w", err)
	}

	return spec, err
}

// loadXdpObjects loads xdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpObjects
//	*xdpPrograms
//	*xdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpSpecs struct {
	xdpProgramSpecs
	xdpMapSpecs
	xdpVariableSpecs
}

// xdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpProgramSpecs struct {
	XdpFirewallFunc *ebpf.ProgramSpec `ebpf:"xdp_firewall_func"`
}

// xdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpMapSpecs struct {
	ActiveGenerationMap *ebpf.MapSpec `ebpf:"active_generation_map"`
	AuditRingbuf        *ebpf.MapSpec `ebpf:"audit_ringbuf"`
	CgroupIdentityMap   *ebpf.MapSpec `ebpf:"cgroup_identity_map"`
	LpmBlocklist        *ebpf.MapSpec `ebpf:"lpm_blocklist"`
	PortRulesMap        *ebpf.MapSpec `ebpf:"port_rules_map"`
	XdpStatsMap         *ebpf.MapSpec `ebpf:"xdp_stats_map"`
}

// xdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpVariableSpecs struct {
}

// xdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpObjects struct {
	xdpPrograms
	xdpMaps
	xdpVariables
}

func (o *xdpObjects) Close() error {
	return _XdpClose(
		&o.xdpPrograms,
		&o.xdpMaps,
	)
}

// xdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpMaps struct {
	ActiveGenerationMap *ebpf.Map `ebpf:"active_generation_map"`
	AuditRingbuf        *ebpf.Map `ebpf:"audit_ringbuf"`
	CgroupIdentityMap   *ebpf.Map `ebpf:"cgroup_identity_map"`
	LpmBlocklist        *ebpf.Map `ebpf:"lpm_blocklist"`
	PortRulesMap        *ebpf.Map `ebpf:"port_rules_map"`
	XdpStatsMap         *ebpf.Map `ebpf:"xdp_stats_map"`
}

func (m *xdpMaps) Close() error {
	return _XdpClose(
		m.ActiveGenerationMap,
		m.AuditRingbuf,
		m.CgroupIdentityMap,
		m.LpmBlocklist,
		m.PortRulesMap,
		m.XdpStatsMap,
	)
}

// xdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpVariables struct {
}

// xdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpPrograms struct {
	XdpFirewallFunc *ebpf.Program `ebpf:"xdp_firewall_func"`
}

func (p *xdpPrograms) Close() error {
	return _XdpClose(
		p.XdpFirewallFunc,
	)
}

func _XdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_bpf.o
var _XdpBytes []byte
